### PR TITLE
Detecting operative system in updater Makefile to check stat version for obtaining filesize.

### PR DESCRIPTION
**Pull request by gloob**
Hi,

I suffered same problem as defined in issue #11 this is a patch for fixing it based on os detection, so we can add additional check based on platform if needed.

### CODE REVIEW

**Comment by baerwolf** [comment]
Hi gloob.
Thank you very much for this nice patch.
Indeed this needs fixing and I will have a deeper look at the weekend for merging.
Probably we need to catch the Windows users, too. They might not have an "uname"??
Can you please test the contents of the Makefile variable $(OS) ? Perhaps this is more useful.
(On Windows it should be "Windows_NT"?)

BR Stephan

**Comment by gloob** [comment]
Adding global check for operative system in Makefile.inc so it can be used where its included, add the check for Windows using $(OS) and a special check if we are using a linux-like environment like cygwin or mingw.

So now users can compile on raw windows or using other kind of systems over windows.

The only pitfall is the deleting of elements where its present a unix directory separator instead of a windows one. Probably just doing a cd into the directory we want to delete would be enough fix.

**Comment by gloob** [comment]
This actually fix issue #11 and issue #4 that was happening to me with pristine copy of windows 8 plus atmel sdk.

**Comment by baerwolf** [comment]
Hi again.
I merged your patch as a single commit into the master.
However new HEAD is https://github.com/baerwolf/USBaspLoader/commit/cbf935e82115f3e3b1865fb51db67dbb4494ae87 , since Makefile need fixing in case of Windows.

Thanks again,
BR Stephan

**Comment by gloob** [comment]
Glad to see it upstream! Thanks to you for this little piece of engineering.

Cheers,
Ale

**Pull request closed without merging**
